version: "3"
services:
  karmen:
    environment:
      TZ: "America/New_York"
      GITHUB_ACTIONS: "${GITHUB_ACTIONS}"
    hostname: karmen
    image: jrcichra/karmen:sha-51c4c77a
    restart: always
    volumes:
      - "${PWD}/test_config.yml:/config.yml"
    ports:
      - "8080:8080"
  gpio:
    environment:
      TZ: "America/New_York"
      GITHUB_ACTIONS: "${GITHUB_ACTIONS}"
    hostname: gpio
    restart: always
    image: jrcichra/smartcar_gpio${VARIANT}:${SHA}
    depends_on:
      - karmen
  dashcam:
    environment:
      TZ: "America/New_York"
      GITHUB_ACTIONS: "${GITHUB_ACTIONS}"
    hostname: dashcam
    image: jrcichra/smartcar_dashcam${VARIANT}:${SHA}
    restart: always
    volumes:
      - "${PWD}/recordings:/recordings"
    privileged: true
    depends_on:
      - karmen
  transfer:
    environment:
      TZ: "America/New_York"
      GITHUB_ACTIONS: "${GITHUB_ACTIONS}"
    hostname: transfer
    restart: always
    image: jrcichra/smartcar_transfer${VARIANT}:${SHA}
    volumes:
      - "${PWD}/recordings:/recordings"
    depends_on:
      - karmen
  obd-emulator:
    environment:
      TZ: "America/New_York"
      GITHUB_ACTIONS: "${GITHUB_ACTIONS}"
    image: jrcichra/elm327-emulator
    hostname: obd-emulator
    restart: always
    volumes:
      - "/dev/pts:/dev/pts"
      - "${PWD}/obdii/:/obdii/"
    privileged: true
    stdin_open: true
    tty: true
  obdii:
    environment:
      TZ: "America/New_York"
      GITHUB_ACTIONS: "${GITHUB_ACTIONS}"
    hostname: obdii
    restart: always
    image: jrcichra/smartcar_obdii${VARIANT}:${SHA}
    privileged: true
    volumes:
      - "/dev/pts:/dev/pts"
      - "${PWD}/obdii/:/obdii/"
    depends_on:
      - karmen
      - obd-emulator
  nas:
    restart: always
    environment:
      TZ: "America/New_York"
      GITHUB_ACTIONS: "${GITHUB_ACTIONS}"
    hostname: nas
    image: rastasheep/ubuntu-sshd
    volumes:
      - "${PWD}/nas:/recordings"
