version: "3"
services:
  karmen:
    environment:
      TZ: "America/New_York"
      GITHUB_ACTIONS: "${GITHUB_ACTIONS}"
    hostname: karmen
    image: jrcichra/karmen
    restart: always
    environment: 
       KARMEN_CONFIG: "/config.yml"
    ports:
      - "6060:6060"
    volumes:
      - "${PWD}/my_config.yml:/config.yml"
  gpio:
    environment:
      TZ: "America/New_York"
      GITHUB_ACTIONS: "${GITHUB_ACTIONS}"
    hostname: gpio
    restart: always
    image: jrcichra/smartcar_gpio_rpi
    privileged: true
    depends_on:
      - karmen
  dashcam:
    environment:
      TZ: "America/New_York"
      GITHUB_ACTIONS: "${GITHUB_ACTIONS}"
    hostname: dashcam
    image: jrcichra/smartcar_dashcam_rpi
    restart: always
    volumes:
      - "${PWD}/recordings:/recordings"
    privileged: true
    depends_on:
      - karmen
  transfer:
    environment:
      TZ: "America/New_York"
      GITHUB_ACTIONS: "${GITHUB_ACTIONS}"
    hostname: transfer
    restart: always
    image: jrcichra/smartcar_transfer_rpi
    volumes:
      - "${PWD}/recordings:/recordings"
    depends_on:
      - karmen
