version: "3"
services:
  karmen:
    environment:
      TZ: "America/New_York"
      GITHUB_ACTIONS: "${GITHUB_ACTIONS}"
    hostname: karmen
    image: ghcr.io/jrcichra/karmen
    restart: always
    environment: 
       KARMEN_CONFIG: "/config.yml"
    ports:
      - "6060:6060"
    volumes:
      - "${PWD}/my_config.yml:/config.yml"
  gpio:
    environment:
      TZ: "America/New_York"
      GITHUB_ACTIONS: "${GITHUB_ACTIONS}"
    hostname: gpio
    restart: always
    image: ghcr.io/jrcichra/smartcar_gpio_rpi
    privileged: true
    depends_on:
      - karmen
  dashcam:
    environment:
      TZ: "America/New_York"
      GITHUB_ACTIONS: "${GITHUB_ACTIONS}"
    hostname: dashcam
    image: ghcr.io/jrcichra/smartcar_dashcam_rpi
    restart: always
    volumes:
      - "${PWD}/recordings:/recordings"
    privileged: true
    depends_on:
      - karmen
  transfer:
    environment:
      TZ: "America/New_York"
      GITHUB_ACTIONS: "${GITHUB_ACTIONS}"
    hostname: transfer
    restart: always
    image: ghcr.io/jrcichra/smartcar_transfer_rpi
    volumes:
      - "${PWD}/recordings:/recordings"
    depends_on:
      - karmen
  # obdii:
  #   environment:
  #     TZ: "America/New_York"
  #     GITHUB_ACTIONS: "${GITHUB_ACTIONS}"
  #     OBD_DEVICE: "/dev/rfcomm0"
  #   hostname: obdii
  #   restart: always
  #   image: ghcr.io/jrcichra/smartcar_obdii_rpi
  #   privileged: true
  #   volumes:
  #     - "/dev/rfcomm0:/dev/rfcomm0"
  #     - "${PWD}/obdii/:/obdii/"
  #   depends_on:
  #     - karmen
  # # Capturing logs with promtail + loki
  # promtail:
  #   image: grafana/promtail
  #   volumes:
  #     - /var/log:/var/log
  #     - /helios/docker:/var/lib/docker:ro
  #     - ./promtail:/etc/promtail-config/
  #   command: -config.file=/etc/promtail-config/my_promtail.yml