events:
  gpio.key_on:
    - serial:
        - dashcam.start_recording.10:
            - framerate: 10
            - hres: 1280
            - vres: 720
            - rot: 0
        - dashcam.start_preview.10
  gpio.key_off:
    - serial:
        - dashcam.stop_recording.10
        - dashcam.stop_preview.10
        - transfer.transfer_all_footage:
            - hostname: dvrpi
            - username: pi
            - password: test
            - path: /media/5tb/dashcam/recordings/
        - transfer.start_conversion:
            - hostname: dvrpi
            - username: pi
            - password: test
            - path: /media/5tb/dashcam/recordings/
        - gpio.power_off
