name: smartcar CI/CD
on: [push, pull_request]

jobs:
  build-test-alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build & push
        run: |
          bash -x build.sh
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: test smartcar
        run: |
          mkdir ${PWD}/recordings
          mkdir -p ${PWD}/nas/.convert
          docker-compose -f docker-compose-test.yml up &
          sleep 240
          ls -lrth "${PWD}/recordings"
          head -9999 obdii/obdii.log || /bin/true
  build-rpi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build & push
        run: |
          bash -x build.sh rpi
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          INFLUX_URL: ${{ secrets.INFLUX_URL }}
          INFLUX_USERNAME: ${{ secrets.INFLUX_USERNAME }}
          INFLUX_PASSWORD: ${{ secrets.INFLUX_PASSWORD }}
      - name: test smartcar rpi
        run: |
          mkdir ${PWD}/recordings
          mkdir -p ${PWD}/nas/.convert
          docker-compose -f docker-compose-test-rpi.yml up &
          sleep 240
          ls -lrth "${PWD}/recordings"
          head -9999 obdii/obdii.log
